### ISSUE TITLE
CMake as dependency

### ISSUE THREAD

**Issue by juliohm** [gridap/MiniQhull.jl#23]
Can you please comment on the CMake dependency? Why do we need a C compiler when qhull_jll is already provided as a blob? Sorry if I am asking the wrong question, I am not familiar with JuliaWrappers or the jll packages but I thought that they are already precompiled for all platforms?

**Comment by juliohm** [comment]
ping @fverdugo

**Comment by fverdugo** [comment]
Hi @juliohm !

The C api of qhull is based on quite intricate objects which difficult the communication from and to Julia code.

We circumvented this by wrapping the qhull calls in new C functions with a much more simple signature (i.e., with only plane C arrays or C ints/floats as arguments). Then we call these later functions from Julia very easily. HOWEVER, we need to compile them (that's why we use cmake).

One option that has been discussed is to precompile our c wrappers and provide them via BinaryBuilder.

**Comment by juliohm** [comment]
> One option that has been discussed is to precompile our c wrappers and provide them via BinaryBuilder.

That would certainly help a lot. It would facilitate the addition of MiniQhull.jl as a dependency in other projects.

**Comment by juliohm** [comment]
This can be closed now as the binaries are provided by BinaryBuilder.jl 🙏🏽
